### ISSUE TITLE
Bug: Unable to enter new fingerprints

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_device_xiaomi_thyme#1]
这个bug只会出现在使用一段时间的设备上。
bug适用于 crdroid 10.5首次构建 至 20240614 的每个版本（其余没有用过）

如果设备使用指纹解锁一段时间后，如果想要录入新的指纹，会遇到下图中的情况：

![Screenshot_20240616-232910_设置](https://github.com/crdroidandroid/android_device_xiaomi_thyme/assets/66206988/3b2d7a26-5825-4042-86db-e337064e03f8)

无论如何尝试添加新指纹总是会是失败的。

---

不过，非常有趣的是，如果启用多用户，并新建一个用户，此时为这个新用户创建指纹是没有任何问题的。
~~临时解决方法目前似乎只有删除掉根目录下的`/data_mirror`文件夹内的文件，但是这会导致失去所有应用数据。~~

**Comment by gwolf2u** [comment]
not proper place to report bugs
also use english please

**Comment by ghost** [comment]
> not proper place to report bugs
> also use english please

Oh, I'm so sorry.
The reason I used Chinese is because Maintainer is good at Chinese.
Feedback here is because the only feedback method given by crdroid or xda is telegram, and it so happens that I don't have telegram.

**Comment by gwolf2u** [comment]
all the more we enforce use of some forum (xda usually, but not mandatory)
no need to use telegram
